### PR TITLE
chore: sq should not exist on public repo

### PR DESCRIPTION
**Pull request by kurtaking**
We should not have Sonarqube configured for public repositories.

### CODE REVIEW

**Comment by timofeee** [comment]
Is there a problem with having SQ in a public repo?

**Comment by jmeridth** [comment]
@timofeee @m-graf pinged you directly.  Will update this PR with results.  Thank you for inquiring.

**Comment by m-graf** [comment]
Thank you for that; but I'm more thankful that you mentioned updating this comment body here to reflect the future outcome, thank you for preserving history here!

**Comment by jmeridth** [comment]
@m-graf Due to security concerns on this public repository the conversation and results may still be filtered.  Thank you for your understanding.

**Comment by jmeridth** [comment]
Result of conversation: We'll setup CodeQL on this repository once it moves over to github.com/procore-oss GitHub organization and remove sonarqube.  We'll be moving to GitHub Actions and deprecating CirleCI, so it will handle the contents of this PR.  

Thank you to @timofeee and @m-graf for asking great questions and ensuring we choose a good path forward.

**Pull request merged**
