### PR TITLE
add formatter per request

### LINKED ISSUE #34: CSV POST Requests fail
Attempting to use the sdk with a `POST` request for a CSV endpoint results in an error due to the immediate conversion of a response to json here:

https://github.com/procore/js-sdk/blob/90304538e483705fd799803761efef3c342dd328/lib/client.ts#L55-L64

It appears that the sdk does not support non-JSON response types. It would be very useful to be able to configure how the sdk handles a given request, instead of assuming we always want to use it for JSON.

### PR DESCRIPTION
**Pull request by yordis**
fixes #34

## Usage

```tsx
// plain text for CVS responses, or you could parse the response with some library
function formatter(response) {
  return response.text()
}
 
procore.get(myCSVEndpoint(), { formatter }),
```

### CODE REVIEW

**Comment by yordis** [comment]
cc: @mrcola91

**Review by mrcola91 — APPROVED** [review]

**Comment by yordis** [comment]
@mrcola91 btw, don't forget I can't merge the PR, so I will leave the process of closing the PR to you.

**Review by chriszhangusc — APPROVED** [review]

**Review by andersontr15 — APPROVED** [review]

**Review by bionikspoon — APPROVED** [review]

**Comment by mrcola91** [comment]
@yordis should we bump the sdk version? Possibly minor since it's adding a new feature, not really patching a bug.

**Comment by yordis** [comment]
@mrcola91 release a new version

**Review by mrcola91 — APPROVED** [review]

**Review by chriszhangusc — APPROVED** [review]
@yordis Bruh

**Pull request merged**
